FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    crossbuild-essential-arm64 \
    pkg-config

WORKDIR /project

# Use ARM64 toolchain
ENV TOOLCHAIN_FILE=/project/cmake/arm64-toolchain.cmake

CMD ["make", "BUILD_DIR=build-arm64", "SDL_BUILD=0"]